<a href="https://colab.research.google.com/github/RubenCameroAmador/Arbol_Genealogico/blob/master/AlgoritmoAasterisco.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matriz de adyacencia estática por ahora 

Omar pon lo que hiciste en la celda de código siguiente


In [3]:
############# settings, dependencies and libraries 
!pip install pytesseract
!pip install pillow
!sudo apt install tesseract-ocr
from PIL import Image
import cv2
import sys 
import pytesseract as tess
import numpy as np
tess.pytesseract.tesseract_cmd = (r'/usr/bin/tesseract')
##################### Upload image and convert image to string
img=Image.open('test.bmp')
text=tess.image_to_string(img)
f=text.split('\n')
##################### Deletion of extra characters 
f1=[]
for i in range(len(f)):
  if('1' in f[i] or '2' in f[i] or '3' in f[i] or '4' in f[i] or '5' in f[i] or '6' in f[i] or '7' in f[i] or '8' in f[i] or '9' in f[i] or '0' in f[i]):
    f1.append(f[i])
f2=[]
#################### Converts array string to integer
for i in range(len(f1)):
  f3=''
  for j in range(len(f1[i])):
    if((f1[i])[j]=='1' or (f1[i])[j]=='2'or (f1[i])[j]=='3'or (f1[i])[j]=='4'or (f1[i])[j]=='5'or (f1[i])[j]=='6'or (f1[i])[j]=='7'or (f1[i])[j]=='8'or (f1[i])[j]=='9'or (f1[i])[j]=='0'or (f1[i])[j]=='\n'or (f1[i])[j]==' '):
      f3=f3+(f1[i])[j]
  f2.append(f3.split(' '))
######## this is the array
m=np.asarray(f2, dtype=int)
print(m)

Reading package lists... Done
Building dependency tree       
Reading state information... Done
tesseract-ocr is already the newest version (4.00~git2288-10f4998a-2).
The following package was automatically installed and is no longer required:
  libnvidia-common-440
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
[[ 0 60 57  0  0 67 19  0  0 92]
 [18 29  0 15  0  0 59 11 36 83]
 [ 0 23  0  0  0 17 42 57 54  0]
 [30  0  0 41 93 34  0  0 13  0]
 [13  0 89  0 60  4  8 39  0  7]
 [ 0  0 37  0 29  0  0  0  0 88]
 [24 51  0 58  0 76  0 96 45 87]
 [ 0  0 78 38  0  0 42 10  0 41]
 [19 70  0  0 78  0 86 49 12  0]
 [ 0  0  0  0 40 49 44  7  0  0]]


Implementación de la **Heuristica** basada en el algoritmo Dijktra Para encontrar la ruta mínima entre dos vertices A,B

In [4]:

##################
her_tem = np.zeros((len(m),2),dtype=int)
her = np.zeros((len(m)),dtype=float)
nodes = np.zeros(len(m),dtype=int)
for i in range(0,len(m)):
    nodes[i]=i
#################

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [[0 for column in range(vertices)] 
                    for row in range(vertices)] 

    def printSolution(self, dist): 
        #print("Vertex \tDistance from Source")
        for node in range(self.V): 
            #print(node, "\t", dist[node])
            her_tem[node,0]=node
            her_tem[node,1]=dist[node]
            
            


    def minDistance(self, dist, sptSet): 
        min = float("inf") 
        for v in range(self.V): 
            if dist[v] < min and sptSet[v] == False: 
                min = dist[v] 
                min_index = v 
        return min_index 
 
    def dijkstra(self, src, des): 

        dist = [float("inf")] * self.V 
        dist[src] = 0
        sptSet = [False] * self.V 

        for cout in range(self.V): 
            u = self.minDistance(dist, sptSet) 
            sptSet[u] = True
            for v in range(self.V): 
                if self.graph[u][v] > 0 and sptSet[v] == False and dist[v] > dist[u] + self.graph[u][v]: 
                        dist[v] = dist[u] + self.graph[u][v] 

        self.printSolution(dist)
        #print(her_tem)
        if(her_tem[des,1]!=0):
          her[src]=her_tem[des,1]-.3

MAIN 
La respuesta resulta de calcular la distancia mínima de todos los nodos a determinado vertice destino, como lo desarrollado en la clase

In [5]:
m[0,9]=0
print(m)
v2 = int(len(m)-1)
g = Graph(len(m)) 
g.graph=m
print('******HEURISTICA********')
for i in range(0,len(m)):
    g.dijkstra(i, v2)
print('nodos', nodes)
print('Heuristica',her)

[[ 0 60 57  0  0 67 19  0  0  0]
 [18 29  0 15  0  0 59 11 36 83]
 [ 0 23  0  0  0 17 42 57 54  0]
 [30  0  0 41 93 34  0  0 13  0]
 [13  0 89  0 60  4  8 39  0  7]
 [ 0  0 37  0 29  0  0  0  0 88]
 [24 51  0 58  0 76  0 96 45 87]
 [ 0  0 78 38  0  0 42 10  0 41]
 [19 70  0  0 78  0 86 49 12  0]
 [ 0  0  0  0 40 49 44  7  0  0]]
******HEURISTICA********
nodos [0 1 2 3 4 5 6 7 8 9]
Heuristica [102.7  51.7  52.7  69.7   6.7  35.7  86.7  40.7  84.7   0. ]


A* Algoritmo 

In [21]:
iteracion = 1
nodo=0
#nodo,acum,heuristica
padre = [[0,m[nodo,nodo],her[nodo]]]
#padre,nodo,acum,heuristica
hijos = []
print('Atributos del Vector Padre: [nodo,acum,heuristica]')
print('Atributos del Vector Hijos: [padre,nodo,acum,heuristica]')
while(nodo!=len(m)-1):
  print('ITERACIÓN',iteracion)
  for i in range(0,len(m)):
    if(i!=nodo and m[nodo,i]!=0):
      sw=False
      j=0
      acum=0
      while(sw==False and j<len(padre)):
        if(padre[j][0]==nodo):
          sw=True
          acum=padre[j][1]+m[nodo][i]
        j+=1
      hijos.append([nodo,i,acum,her[i]])
  iteracion+=1
  #print('nodo-acum-heuristica')
  print('PADRE',padre)
  #print('padre-nodo-acum-heuristica')
  print('HIJOS',hijos)

  ##Calculo del hijo menor y nuevo padre
  menor=hijos[0][2]+hijos[0][3]
  hijomenor=hijos[0][1]
  for son in range(0,len(hijos)):
    testmenor=(hijos[son][2]+hijos[son][3])
    if(menor>testmenor):
      hijomenor=hijos[son][1]
      menor=testmenor
      posmenor=son
  # print('El hijo menor de cero es: ',hijomenor)
  #print('Con un valor de: ',menor)
  #print('La posicion en vector del menor es: ',posmenor)
  padre.append([hijomenor,hijos[posmenor][2],her[hijomenor]])
  #print('Esta sería la nueva lista de padres',padre)
  del hijos[posmenor]
  #print('El nuevo vector de hijos es: ',hijos)
  print('El valor del nodo es : ',hijomenor)
  nodo=hijomenor
print()
print('***RESULTADOS FINALES***')
print('Vector padres final',padre)
print('El camino obtenido es el siguiente de izquierda a derecha')
for k in range(0,len(padre)):
  print(padre[k][0],' ', end="")
print('Con distancia acumulada de: ',padre[len(padre)-1][1], "e Heuristica preestablecida de: ",her[0])


    



Atributos del Vector Padre: [nodo,acum,heuristica]
Atributos del Vector Hijos: [padre,nodo,acum,heuristica]
ITERACIÓN 1
PADRE [[0, 0, 102.7]]
HIJOS [[0, 1, 60, 51.7], [0, 2, 57, 52.7], [0, 5, 67, 35.7], [0, 6, 19, 86.7]]
El valor del nodo es :  5
ITERACIÓN 2
PADRE [[0, 0, 102.7], [5, 67, 35.7]]
HIJOS [[0, 1, 60, 51.7], [0, 2, 57, 52.7], [0, 6, 19, 86.7], [5, 2, 104, 52.7], [5, 4, 96, 6.7], [5, 9, 155, 0.0]]
El valor del nodo es :  4
ITERACIÓN 3
PADRE [[0, 0, 102.7], [5, 67, 35.7], [4, 96, 6.7]]
HIJOS [[0, 1, 60, 51.7], [0, 2, 57, 52.7], [0, 6, 19, 86.7], [5, 2, 104, 52.7], [5, 9, 155, 0.0], [4, 0, 109, 102.7], [4, 2, 185, 52.7], [4, 5, 100, 35.7], [4, 6, 104, 86.7], [4, 7, 135, 40.7], [4, 9, 103, 0.0]]
El valor del nodo es :  9

***RESULTADOS FINALES***
Vector padres final [[0, 0, 102.7], [5, 67, 35.7], [4, 96, 6.7], [9, 103, 0.0]]
El camino obtenido es el siguiente de izquierda a derecha
0  5  4  9  Con distancia acumulada de:  103 e Heuristica preestablecida de:  102.7
